servers:
  local:
    ip: 127.0.0.1
    port: 8001
  real:
    ip: 106.243.26.78
    port: 80

spring:
  session:
    jdbc:
      initialize-schema: always
  profiles:
    include: oauth
  datasource:
    url: jdbc:mariadb://letscoding.kr:3306/lets
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: Gudrn!@09
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    
    